In [109]:
import numpy as np

In [112]:
npzfile = np.load('shuffled_train.npz')
print(npzfile.files)
X_train = npzfile['arr_0']
y_train = npzfile['arr_1']
print(X_train.shape, y_train.shape)

['arr_0', 'arr_1']
(3198, 640, 128) (3198,)


In [113]:
npzfile = np.load('shuffled_valid.npz')
print(npzfile.files)
X_valid = npzfile['arr_0']
y_valid = npzfile['arr_1']
print(X_valid.shape, y_valid.shape)

['arr_0', 'arr_1']
(400, 640, 128) (400,)


In [115]:
print(y_train.shape)
print(y_train[:5])
print(y_valid.shape)
print(y_valid[:5])

(3198,)
[3 0 0 2 1]
(400,)
[1 0 0 0 2]


In [116]:
def identity_vector(n):
    return np.identity(4, dtype=int)[n].tolist()

In [117]:
def to_binary_matrix(vector):
    matrix = np.empty((0, 4), int)
    for n in vector:
        v = identity_vector(n)
        matrix = np.append(matrix, [v], axis=0)
    return matrix

In [118]:
y_train_matrix = to_binary_matrix(y_train)
y_valid_matrix = to_binary_matrix(y_valid)

In [119]:
print(y_train_matrix.shape)
print(y_train_matrix[:5])
print(y_valid_matrix.shape)
print(y_valid_matrix[:5])

(3198, 4)
[[0 0 0 1]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]]
(400, 4)
[[0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 1 0]]


In [120]:
np.savez('shuffled_train_fixed', X_train, y_train_matrix)
np.savez('shuffled_valid_fixed', X_valid, y_valid_matrix)